name: rnd_flutter_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  email_validator: ^2.1.17
  getwidget: ^3.0.1
  provider: ^6.0.5
  datetime_picker_formfield: ^2.0.1
  intl: ^0.18.0
  flutter_spinkit: ^5.2.0
  contacts_service: ^0.6.2
  fluttercontactpicker: ^4.7.0
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.4+4
  flutter_profile_picture: ^2.0.0
  pinput: ^2.2.31
  carousel_slider: ^4.0.0
  cool_alert: ^2.0.1
  shared_preferences: ^2.1.2
  fluttertoast: ^8.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
    - assets/images/tcash.png
    - assets/icons/
